ALTER TABLE Implementation DROP FOREIGN KEY FKImplementa72807;
ALTER TABLE Course DROP FOREIGN KEY FKCourse761634;
ALTER TABLE Curriculum DROP FOREIGN KEY FKCurriculum780269;
ALTER TABLE subGroup_imp DROP FOREIGN KEY FKsubGroup_i544369;
ALTER TABLE subGroup_imp DROP FOREIGN KEY FKsubGroup_i539363;
ALTER TABLE Room_imp DROP FOREIGN KEY FKRoom_imp242407;
ALTER TABLE Room_imp DROP FOREIGN KEY FKRoom_imp438424;
ALTER TABLE Teacher_Imp DROP FOREIGN KEY FKTeacher_Im796240;
ALTER TABLE Teacher_Imp DROP FOREIGN KEY FKTeacher_Im763706;
ALTER TABLE subGroup DROP FOREIGN KEY FKsubGroup503478;
ALTER TABLE Teacher_degreeprogram DROP FOREIGN KEY FKTeacher_de290315;
ALTER TABLE Teacher_degreeprogram DROP FOREIGN KEY FKTeacher_de96473;
DROP TABLE IF EXISTS Curriculum;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Implementation;
DROP TABLE IF EXISTS Teacher;
DROP TABLE IF EXISTS Degreeprogram;
DROP TABLE IF EXISTS subGroup;
DROP TABLE IF EXISTS subGroup_imp;
DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS Room_imp;
DROP TABLE IF EXISTS Teacher_Imp;
DROP TABLE IF EXISTS Teacher_degreeprogram;
CREATE TABLE Curriculum (id int(10) NOT NULL AUTO_INCREMENT, Name varchar(255), Degreeprogramid int(10) NOT NULL, PRIMARY KEY (id), UNIQUE INDEX (id)) CHARACTER SET UTF8;
CREATE TABLE Course (id int(10) NOT NULL AUTO_INCREMENT, Code varchar(255) NOT NULL, Name varchar(255), Changes varchar(255), Languages varchar(255), Credit int(10), Amount int(10), P1 int(10), P2 int(10), P3 int(10), P4 int(10), P5 int(10), Total int(10), Curriculumid int(10) NOT NULL, PRIMARY KEY (id), UNIQUE INDEX (id), INDEX (Code)) CHARACTER SET UTF8;
CREATE TABLE Implementation (id int(10) NOT NULL AUTO_INCREMENT, Courseid int(10) NOT NULL, PRIMARY KEY (id), UNIQUE INDEX (id)) CHARACTER SET UTF8;
CREATE TABLE Teacher (id int(10) NOT NULL AUTO_INCREMENT, Code varchar(255) NOT NULL, Name varchar(255), PRIMARY KEY (id), UNIQUE INDEX (id), UNIQUE INDEX (Code)) CHARACTER SET UTF8;
CREATE TABLE Degreeprogram (id int(10) NOT NULL AUTO_INCREMENT, Code varchar(255) NOT NULL, Name varchar(255), PRIMARY KEY (id), UNIQUE INDEX (id), UNIQUE INDEX (Code)) CHARACTER SET UTF8;
CREATE TABLE subGroup (id int(10) NOT NULL AUTO_INCREMENT, Code varchar(255) NOT NULL, Department int(10), Groupid int(10) NOT NULL, Degreeprogramid int(10) NOT NULL, PRIMARY KEY (id), UNIQUE INDEX (id), UNIQUE INDEX (Code)) CHARACTER SET UTF8;
CREATE TABLE subGroup_imp (subGroupid int(10) NOT NULL, Implementationid int(10) NOT NULL, PRIMARY KEY (subGroupid, Implementationid)) CHARACTER SET UTF8;
CREATE TABLE Room (id int(10) NOT NULL AUTO_INCREMENT, Code varchar(255) NOT NULL, Seats int(10), Topic varchar(255), PRIMARY KEY (id), UNIQUE INDEX (id), UNIQUE INDEX (Code)) CHARACTER SET UTF8;
CREATE TABLE Room_imp (Roomid int(10) NOT NULL, Implementationid int(10) NOT NULL, PRIMARY KEY (Roomid, Implementationid)) CHARACTER SET UTF8;
CREATE TABLE Teacher_Imp (Teacherid int(10) NOT NULL, Implementationid int(10) NOT NULL, PRIMARY KEY (Teacherid, Implementationid)) CHARACTER SET UTF8;
CREATE TABLE Teacher_degreeprogram (Teacherid int(10) NOT NULL, Degreeprogramid int(10) NOT NULL, PRIMARY KEY (Teacherid, Degreeprogramid)) CHARACTER SET UTF8;
ALTER TABLE Implementation ADD INDEX FKImplementa72807 (Courseid), ADD CONSTRAINT FKImplementa72807 FOREIGN KEY (Courseid) REFERENCES Course (id);
ALTER TABLE Course ADD INDEX FKCourse761634 (Curriculumid), ADD CONSTRAINT FKCourse761634 FOREIGN KEY (Curriculumid) REFERENCES Curriculum (id);
ALTER TABLE Curriculum ADD INDEX FKCurriculum780269 (Degreeprogramid), ADD CONSTRAINT FKCurriculum780269 FOREIGN KEY (Degreeprogramid) REFERENCES Degreeprogram (id);
ALTER TABLE subGroup_imp ADD INDEX FKsubGroup_i544369 (subGroupid), ADD CONSTRAINT FKsubGroup_i544369 FOREIGN KEY (subGroupid) REFERENCES subGroup (id);
ALTER TABLE subGroup_imp ADD INDEX FKsubGroup_i539363 (Implementationid), ADD CONSTRAINT FKsubGroup_i539363 FOREIGN KEY (Implementationid) REFERENCES Implementation (id);
ALTER TABLE Room_imp ADD INDEX FKRoom_imp242407 (Roomid), ADD CONSTRAINT FKRoom_imp242407 FOREIGN KEY (Roomid) REFERENCES Room (id);
ALTER TABLE Room_imp ADD INDEX FKRoom_imp438424 (Implementationid), ADD CONSTRAINT FKRoom_imp438424 FOREIGN KEY (Implementationid) REFERENCES Implementation (id);
ALTER TABLE Teacher_Imp ADD INDEX FKTeacher_Im796240 (Teacherid), ADD CONSTRAINT FKTeacher_Im796240 FOREIGN KEY (Teacherid) REFERENCES Teacher (id);
ALTER TABLE Teacher_Imp ADD INDEX FKTeacher_Im763706 (Implementationid), ADD CONSTRAINT FKTeacher_Im763706 FOREIGN KEY (Implementationid) REFERENCES Implementation (id);
ALTER TABLE subGroup ADD INDEX FKsubGroup503478 (Degreeprogramid), ADD CONSTRAINT FKsubGroup503478 FOREIGN KEY (Degreeprogramid) REFERENCES Degreeprogram (id);
ALTER TABLE Teacher_degreeprogram ADD INDEX FKTeacher_de290315 (Teacherid), ADD CONSTRAINT FKTeacher_de290315 FOREIGN KEY (Teacherid) REFERENCES Teacher (id);
ALTER TABLE Teacher_degreeprogram ADD INDEX FKTeacher_de96473 (Degreeprogramid), ADD CONSTRAINT FKTeacher_de96473 FOREIGN KEY (Degreeprogramid) REFERENCES Degreeprogram (id);
